main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carousel/', include('main.urls'), name="main"),
    path('v8/', include('story8.urls'), name="story8"),
    path('', include('userauth.urls'), name="userauth"),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', views.api, name='api'),
]

userauth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'userauth'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(
        template_name='userauth-login.html',
        redirect_field_name='userauth:index',
    ), name='login'),
    path('register', views.register, name='register'),
    path('logout', views.user_logout, name='logout'),
    path('', views.index, name='index'),
]

main/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

userauth/models.py
from django.db import models

# Create your models here.

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "main-index.html")

story8/views.py
from django.core import serializers
from django.shortcuts import render
from django.test.client import Client
from django.http import JsonResponse
import urllib3
import json

# Create your views here.
def index(request):
    return render(request, "story8-index.html")

def api(request):
    query = dict(request.GET)
    if (q := query.get('q')):
        query['q'] = q[0]
    if (q := query.get('startIndex')):
        query['startIndex'] = q[0]
        
    response = urllib3.PoolManager().request(
        'GET',
        'https://www.googleapis.com/books/v1/volumes',
        fields=query
    )
    context = json.loads(response.data.decode('utf-8'))
    return JsonResponse(context)

userauth/views.py
from .forms import CreateUserForm
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm


# Create your views here.
def register(request):
    context = {
        'auth': True
    }
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form.save()
            return redirect('userauth:login')

    else:
        context['form'] = CreateUserForm()

    return render(request, 'userauth-register.html', context=context)

def index(request):
    return render(request, 'userauth-secret.html')


def user_logout(request):
    logout(request)
    return redirect('userauth:login')

main/templates/main-index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>About Me!</title>
<meta name="description" content="About Dennis">

<meta property="og:title" content="About Me!">
<meta property="og:type" content="website">
<meta property="og:site_name" content="About Dennis">
{% endblock head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/wave.css' %}">
{% endblock style %}

{% block script_head %}
{% comment %} Fontawesome icons {% endcomment %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% comment %} jQuery {% endcomment %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="module">import html5sortable from 'https://cdn.skypack.dev/html5sortable';</script>
{% endblock script_head %}

{% block content %}
<h1>About me!</h1>

<ul class="accordion">

  <li>
    <div class="accord-item">
      <a href="#">Recent Activity</a>
      <div class="expand"><i class="fas fa-plus"></i></div>
      <div class="control">
        <i class="fas fa-chevron-up"></i>
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
    <div class="inner">
      <article>
        <ul>
          <li>I'm currently pursuing a Computer Science degree in Universitas Indonesia</li>
          <li><g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">💻</g-emoji> I’m currently working on <a href="https://github.com/project-roar">Project Roar</a> and <strong>Unnamed Next.JS Blog Framework</strong></li>
          <li><g-emoji class="g-emoji" alias="seedling" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f331.png">🌱</g-emoji> I’m currently learning Typescript, Deno <g-emoji class="g-emoji" alias="sauropod" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f995.png">🦕</g-emoji>, algorithms, web development with Django</li>
          <li>I also explore GitHub occasionally</li>
        </ul>
      </article>
    </div>
  </li>

  <li>
    <div class="accord-item">
      <a href="#">Organizations/Comitee Experiences</a>
      <div class="expand"><i class="fas fa-plus"></i></div>
      <div class="control">
        <i class="fas fa-chevron-up"></i>
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
    <div class="inner">
      <article>
        <ul>
          <li>Akademis Maung - Member</li>
          <li>DDP0 - Head of Acedemic</li>
          <li>PMB Fasilkom UI 2020 - Mentor</li>
          <li>Developer Student Club Universitas Indonesia - Core Team</li>
        </ul>
        See more on my <a href="https://www.linkedin.com/in/denniswd/">LinkedIn</a>
      </article>
    </div>
  </li>

  <li>
    <div class="accord-item">
      <a href="#">Achievement</a>
      <div class="expand"><i class="fas fa-plus"></i></div>
      <div class="control">
        <i class="fas fa-chevron-up"></i>
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
    <div class="inner">
      <article>
      <ul>
        <li>Survived 1st term of college</li>
        <li>Survived 2nd term of college</li>
        <li>Maybe you should check my projects on my <a href="https://github.com/dnswd?tab=repositories">GitHub</a></li>
      </ul>
      </article>
    </div>
  </li>

  <li>
    <div class="accord-item">
      <a href="#">My Favorite Playlist</a>
      <div class="expand"><i class="fas fa-plus"></i></div>
      <div class="control">
        <i class="fas fa-chevron-up"></i>
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
    <div class="inner">
      <article>
        <p style="margin-top: 0">I can't sleep sometimes, so to face that issue I usually listen to these songs.</p>
        <iframe src="https://open.spotify.com/embed/playlist/2hRK0EPufLi1g8QWijDg7b" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      </article>
    </div>
  </li>

  <li>
    <div class="accord-item">
      <a href="#">Contact me!</a>
      <div class="expand"><i class="fas fa-plus"></i></div>
      <div class="control">
        <i class="fas fa-chevron-up"></i>
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
    <div class="inner">
      <article>
        <ul>
          <li><a href="https://www.linkedin.com/in/denniswd/" rel="nofollow">LinkedIn</a></li>
          <li><a href="https://twitter.com/dawalangadi" rel="nofollow">Twitter</a></li>
          <li><a href="https://line.me/R/ti/p/dennisaw2000" rel="nofollow">Line Messenger</a></li>
          <li><a href="mailto:dennisaw2000@gmail.com">Email</a></li>
          <li><a href="mailto:dennis.al@ui.ac.id">Academic Email</a></li>
        </ul>
      </article>
    </div>
  </li>

</ul>

<div class="waveWrapper waveAnimation">
  <div class="waveWrapperInner bgTop">
    <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')"></div>
  </div>
  <div class="waveWrapperInner bgMiddle">
    <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')"></div>
  </div>
  <div class="waveWrapperInner bgBottom">
    <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')"></div>
  </div>
</div>
{% endblock content %}

{% block script_foot %}
<script src={% static 'js/script.js' %}></script>
{% endblock script_foot %}

story8/templates/story8-index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Simple Book Finder!</title>
<meta name="description" content="Find book!">

<meta property="og:title" content="Find Books!">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Find Books!">
{% endblock head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/wave.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/story8_style.css' %}">
{% endblock style %}

{% block script_head %}
{% comment %} Fontawesome icons {% endcomment %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% comment %} jQuery {% endcomment %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block content %}
<div class="jumbotron">
  <h1>Find books!</h1>
  <div class="searchbox">
    <input class="search drop-card" type="text" id="query" name="query" placeholder="Search for book title or author..."/>
  </div>
</div>

<div class="content-wrapper">
  {% comment %} 
  <div class="inner drop-card">
    <div class="description">
    <h4>Title</h4>
      <ul>
        <li>Title</li>
        <li>Publisher</li>
        <li>Categories</li>
        <li>Author (optional)</li>
        <li>Published date</li>
        <li>ISBN 13 / 10</li>
      </ul>
    </div>
  </div> 
  {% endcomment %}

</div>

<a>
  <div class="jumbotron">
    <button class="search">Next</button>
  </div>
</a>

<div class="waveWrapper waveAnimation">
  <div class="waveWrapperInner bgTop">
    <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')"></div>
  </div>
  <div class="waveWrapperInner bgMiddle">
    <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')"></div>
  </div>
  <div class="waveWrapperInner bgBottom">
    <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')"></div>
  </div>
</div>
{% endblock content %}

{% block script_foot %}
<script src={% static 'js/book_script.js' %}></script>
{% endblock script_foot %}

templates/base.html
<!DOCTYPE html>

{% load static %}

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block head %}
        {% endblock head %}

        {% block script_head %}
        {% endblock script_head %}

        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% block body %}
        <div id="page-container">
            <div id="content-wrap">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        {% endblock body %}
        
        {% block script_foot %}
        {% endblock script_foot %}
    </body>
</html>

userauth/templates/userauth-login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block head %}
<title>Login pls</title>
<meta name="description" content="Login to this site!">

<meta property="og:title" content="Login">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Story9">
{% endblock head %}

{% block script_head %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/wave.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock style %}

{% block body %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<div class="login-dark" style="height: 695px;">
    <form class="form-signin" method="POST">
    {% csrf_token %}
      <h2 class="card-title">Login</h2>
      <div class="form-group form-label-group">{% render_field form.username class="form-control" placeholder="Username" %}</div>
      <div class="form-group form-label-group">{% render_field form.password class="form-control" placeholder="Password" %}</div>
      <div class="form-group form-label-group"><button class="btn btn-primary btn-block">Log In</button></div>
      <a class="forgot" href={% url 'userauth:register' %}>Haven't registered yet?</a>
    </form>
</div>

<div class="waveWrapper waveAnimation">
  <div class="waveWrapperInner bgTop">
    <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')"></div>
  </div>
  <div class="waveWrapperInner bgMiddle">
    <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')"></div>
  </div>
  <div class="waveWrapperInner bgBottom">
    <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')"></div>
  </div>
</div>
{% endblock body %}

{% block script_foot %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% endblock script_foot %}

userauth/templates/userauth-register.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block head %}
<title>Register pls</title>
<meta name="description" content="Login to this site!">

<meta property="og:title" content="Login">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Story9">
{% endblock head %}

{% block script_head %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/wave.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock style %}

{% block body %}

<div class="login-dark" style="height: 695px;">
    <form class="form-signin" method="POST">
        <h2 class="card-title">Register</h2>
        {% csrf_token %}
        <div class="form-group form-label-group">{% render_field form.username class="form-control" placeholder="Username" %}</div>
        <div class="form-group form-label-group">{% render_field form.email class="form-control" placeholder="Email" %}</div>
        <div class="form-group form-label-group">{% render_field form.password1 class="form-control" placeholder="Password" %}</div>
        <div class="form-group form-label-group">{% render_field form.password2 class="form-control" placeholder="Retype password" %}</div>
        <div class="form-group form-label-group"><button class="btn btn-primary btn-block">Register</button></div><a class="forgot" href={% url 'userauth:login' %}>Already have an account?</a>
    </form>
</div>

<div class="waveWrapper waveAnimation">
  <div class="waveWrapperInner bgTop">
    <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')"></div>
  </div>
  <div class="waveWrapperInner bgMiddle">
    <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')"></div>
  </div>
  <div class="waveWrapperInner bgBottom">
    <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')"></div>
  </div>
</div>
{% endblock body %}

{% block script_foot %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% endblock script_foot %}

userauth/templates/userauth-secret.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block head %}
<title>Login pls</title>
<meta name="description" content="Login to this site!">

<meta property="og:title" content="Login">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Story9">
{% endblock head %}

{% block script_head %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/wave.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock style %}

{% block body %}

<div class="mx-auto" style="width: 50%;">
  <div class="mystery text-center" style="padding-top: 30vh; color: #ffff">
    {% if request.user.is_authenticated %}
    <h1>Hello, {{request.user.username}}!</h1>
    <h3>Here's your wisdom</h3>
    <p id="quote">Your will have a great IPK this semester!</p>
    <i><p id="author">Believe in yourself!</p>
    <div class="pt-5">
      <a href={% url 'userauth:logout' %}>
        <button type="button" class="btn btn-danger mx-auto" style="width: 50%">Logout</button>
      </a>
    </div>
    {% else %}
    <h1>Psstt, wanna hear some wisdom?</h1>
    <div class="pt-5">
      <a href={% url 'userauth:login' %}>
        <button type="button" class="btn btn-primary mx-auto" style="width: 50%">Login</button>
      </a>
    </div>
    {% endif %}
  </div>
</div>


<div class="waveWrapper waveAnimation">
  <div class="waveWrapperInner bgTop">
    <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')"></div>
  </div>
  <div class="waveWrapperInner bgMiddle">
    <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')"></div>
  </div>
  <div class="waveWrapperInner bgBottom">
    <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')"></div>
  </div>
</div>
{% endblock body %}

{% block script_foot %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js" integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ==" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% endblock script_foot %}